### ISSUE TITLE
JSON Issue report ms

### ISSUE THREAD

**Issue by n1xqe** [E-Edu/e-edu.github.io-concept#38]
## Microservice
report

## Priority
Normal 

## Issue
Old:
```json
[
    {
        "ticket_id": "string",
        "task_id": "string",
        "sender": "string",
        "title": "string",
        "body": "string",
        "ticket_type": "string"
    }
]
```
new:
```json
{   
    "data": {
            "ticket_id": "string",
            "task_id": "string",
            "user_id": "string",
            "title": "string",
            "body": "string",
            "ticket_type": "string"
      }
}
```
there is a list not a obj.

**Comment by iiestIT** [comment]
also pref int for the role

**Comment by JavaDerg** [comment]
You "New" example isn't valid JSON, please correct.
Additionaly IDs are Strings because we use UUIDs as IDs.
Int additionaly arenormaly limited to 32 bits, which makes solid unique numbers hard to generate, unless you want to have sequential IDs.
And we will definitivly **not** implement sequential IDs.

**Comment by JavaDerg** [comment]
What endpoint?

**Comment by JavaDerg** [comment]
Issue rejected.
The endpoint you are refering to returns a List, so we need to use a Array. We can not use a object here.
https://github.com/E-Edu/concept/blob/f2627491843fa8668e7d52facfd6581231086d4f/documentation/dev/endpoints/swagger/report.yaml#L119
Additionally if you just want to get a single Object then why are you encapsulating it in another one...?

**Comment by n1xqe** [comment]
@post-rex 
endpoint : /ticket/list
My version is implemented and work great but is not deployed on the server yet. When the new version of the ms is available you get your data in the new format. The current version is not a comparison. Also you can filter easier if it a objekt and it's easier to handle inside the ms.

**Comment by JavaDerg** [comment]
> @post-rex
> endpoint : /ticket/list
> My version is implemented and work great but is not deployed on the server yet. When the new version of the ms is available you get your data in the new format. The current version is not a comparison. Also you can filter easier if it a objekt and it's easier to handle inside the ms.

Then change it. What we made here is what you need to implement.
We don't need to change your stuff because you decided so.
Besides that, the endpoint first of all states in its description that it returns a __list__.
Additionaly the endpoint it literaly named `/ticket/LIST` notice the uppercase text.
No new format, no changes here until there is a actual issue with it.
The issue stays closed and will now be locked.
